[package]
name = "expandable-impl"
version = "0.1.0"
edition = "2021"
description = "Name squatting before releasing my pet project - email me if you're interested by this crate name."
license = "MIT OR Apache-2.0"

[dependencies]
smallvec = "1.11"

[dev-dependencies]
expect-test = "1.4"
